name: dart_ytmusic_api
description: Unofficial YouTube Music Api for dart 
version: 1.3.6
repository: https://github.com/MusilyApp/dart_ytmusic_api

environment:
  sdk: ^3.4.1

dependencies:
  cookie_jar: ^4.0.8
  html: ^0.15.6
  http: ^1.6.0
  universal_io: ^2.2.2

dev_dependencies:
  lints:
  test:
