name: dart_ytmusic_api
description: Unofficial YouTube Music Api for dart 
version: 1.3.5
repository: https://github.com/MusilyApp/dart_ytmusic_api

environment:
  sdk: ^3.4.3

dependencies:
  cookie_jar:
  dio:
  html:
  http:

dev_dependencies:
  lints:
  test:
